### ISSUE TITLE
Possible typo in filter name

### ISSUE THREAD

**Issue by pondermatic** [ideologix/dlm-wp-updater#3]
@gdarko, Is the `wlm_http_get_params` filter in [`IdeoLogix\DigitalLicenseManagerUpdaterWP\Http\Client::_get()`](https://github.com/ideologix/dlm-wp-updater/blob/c05d26f78c3337294cf5fa7949405a25102a3cd9/src/Http/Client.php#L277) supposed to be named `dlm_http_get_params`?

**Comment by gdarko** [comment]
Hi @pondermatic 

Yes - that filter should be changed to use the dlm_ prefix. It's probably a leftover from the old dev name.

Best Regards,
Darko
