### ISSUE TITLE
HTTP cached response is not used by prepareInfo() or prepareValidateLicense()

### ISSUE THREAD

**Issue by pondermatic** [ideologix/dlm-wp-updater#5]
[`IdeoLogix\DigitalLicenseManagerUpdaterWP\Http\Client::prepareInfo()`](https://github.com/ideologix/dlm-wp-updater/blob/1.1.1/src/Http/Client.php#L160-L191) and [`IdeoLogix\DigitalLicenseManagerUpdaterWP\Http\Client::prepareValidateLicense()`](https://github.com/ideologix/dlm-wp-updater/blob/1.1.1/src/Http/Client.php#L193-L224) set HTTP responses in the cache, but never return a cached entry if it hasn't timed out. This causes a request to the DLM software server 1 (or more) times on the WP admin plugin and update pages.

I am happy to work on this issue and submit a pull request if it's OK with you, @gdarko.

**Comment by gdarko** [comment]
Hi @pondermatic  - Thanks for reporting this. Feel free to submit pr, i will review and merge those asap.
